version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - nginx_logs:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  nginx_logs:

networks:
  app_network:
    driver: bridge